export default [
	{
		id: 1,
		tag: 'Для нормальной кожи',
		name: 'Увлажняющий мусс',
		image: 'images/1.jpg',
		description: `<p>Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.</p>`,
		link: 'https://site.com/product/1',
		price: 2750,
		compound: [
			'активные натуральные комплексы',
			'витамины С, А, РР, В И Е',
			'солнцезащитные компоненты',
		],
	},
	{
		id: 2,
		tag: 'Для проблемной кожи',
		name: 'Увлажняющая маска',
		image: 'images/2.jpg',
		description: `<p>Способствует удерживанию влаги в верхних слоях кожи.</p>`,
		link: 'https://site.com/product/2',
		price: 3500,
		compound: [
			'воски',
			'минералы',
			'масла',
		],
	},
	{
		id: 3,
		tag: 'Для жирной кожи',
		name: 'Гель для умывания',
		image: 'images/3.jpg',
		description: `<p>Интенсивно очищает, не повреждает защитный барьер кожи.</p>`,
		link: 'https://site.com/product/3',
		price: 1650,
		compound: [
			'минералы',
			'витамины С, А, РР, В И Е',
			'солнцезащитные компоненты',
		],
	},
	{
		id: 4,
		status: 'new',
		tag: 'Для нормальной кожи',
		name: 'Подарочный набор №1',
		image: 'images/4.jpg',
		description: `<p>Набор, состоящий из увлажняющего крема и маски.</p>`,
		link: 'https://site.com/product/4',
		price: 4750,
		compound: [
			'воски',
			'минералы',
			'масла',
		],
	},
	{
		id: 5,
		status: 'hot',
		tag: 'Для нормальной кожи',
		name: 'Подарочный набор №5',
		image: 'images/5.jpg',
		description: `<p>Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.</p>`,
		link: 'https://site.com/product/5',
		price: 7520,
		compound: [
			'воски',
			'минералы',
			'масла',
		],
	}
]
